### PR TITLE
Switch to input type="text" and @wojtekmaj/predict-input-value package to prevent invalid inputs

### LINKED ISSUE #74: It's possible to enter "99" in minutes input
Input allows to input 99 minutes
Screenshot 2020-01-17 at 1 39 56 PM

I tried to set max value but it did not help.

### LINKED ISSUE #87: Input box shows three digits if a single digit is entered starting with 0 Ex. 01, then it shows 001.
Hi Sir,

I recently used this library and found that when I enter a single digit in the input box so for example if I enter 1 , so it will convert it into 01. Now if I enter as 01 , it converts it into 001, so this is the issue it is converting into three digits by adding a leading 0, which is not correct in this case. Even if I enter 01 or 02 , it should reflect 2 digits only, which is not happening.The input box here I mean hour input box as well as minute input box.Could you please help

### PR DESCRIPTION
**Pull request by wojtekmaj**
Fixes #74
Fixes #87

See also https://github.com/wojtekmaj/react-date-picker/pull/272

TODO: 

* [x] Min/max validation
* [x] Increment/decrement using arrows

### CODE REVIEW

**Comment by tavriaforever** [comment]
any update?

**Review by piyushkathayat — APPROVED** [review]

**Comment by piyushkathayat** [comment]
Hi, @wojtekmaj could you please merge these to the master. This branch has a fix what we needed. Thanks

**Comment by wojtekmaj** [comment]
It's not done, it's missing min/max validation. It can't be merged like that.

**Comment by mohitp22** [comment]
@wojtekmaj max for minute input type is not working  if maxDetail="minute" but when maxDetail="second" max validation working , what the workaround for this

**Pull request closed without merging**
