### PR TITLE
Fixing 508 accessibility errors reported by Wave

### PR DESCRIPTION
**Pull request by Outc4sted**
This PR aims to fix the errors reported by the Wave plugin for 508 accessibility issues. The one error remaining displayed in the screenshot below is from the sample page and is not part of the TimePicker component.

image

### CODE REVIEW

**Comment by nickbristow** [comment]
This is exactly what I was looking for.

https://github.com/wojtekmaj/react-time-picker/issues/21

**Comment by nickbristow** [comment]
@wojtekmaj 
any chance we can get this merged?

**Comment by wojtekmaj** [comment]
Hi, sorry for the delay. I'm afraid we won't be able to merge it in this form, although I'm all for implementing support for Aria labels. The reason of this is because we can't possibly provide proper labels in all languages we support. We could, however, add support for hourAriaLabel, minuteAriaLabel and so on props.

**Comment by wojtekmaj** [comment]
@Outc4sted React-Time-Picker now includes the same implementation as in React-Date-Picker and other packages. It's a little different approach, because we need to support users using all possible locales. Feel free to test it and comment if that suits your needs.

**Pull request closed without merging**
