### PR TITLE
Add support for 12-hour clock

### LINKED ISSUE #3: Support For 12 Hour AM/PM format

### PR DESCRIPTION
**Pull request by wojtekmaj**
Fixes #3.

### CODE REVIEW

**Comment by ro-savage** [comment]
Awesome work on your date and time pickers @wojtekmaj !

Any update on the 12hour PR?

**Comment by wojtekmaj** [comment]
Hi @ro-savage, I still have some unresolved issue with this feature and I'm super busy at the moment, so can't promise anything. Will make sure to keep it as my top priority though!

**Comment by forrestbice** [comment]
Just dropped by to see how things are going with this PR @wojtekmaj any chance this will be worked on soon?

**Comment by wojtekmaj** [comment]
In fact, it's now functionally ready! I just can't get unit tests to work on Travis. It seems to ignore locale for some reason. They pass for me locally :( Any idea what might be wrong here?

**Comment by forrestbice** [comment]
@wojtekmaj great! Which tests specifically are failing? As far as local goes I think you might want to be specifying it in `scripts` of your `package.json`. For example:

```
"test": "export TZ=ETC/UTC && npm run test-eslint && npm run test-jest"
```

**Comment by wojtekmaj** [comment]
Turns out Travis for some reason ignores locale. I prepared a simple test file:

```js
console.log(
  Intl.DateTimeFormat(
    'en-US',
    { hour: 'numeric', minute: 'numeric', second: 'numeric' }
  ).format(new Date(2018, 0, 1, 21, 37, 14))
);

console.log(
  Intl.DateTimeFormat(
    'de-DE',
    { hour: 'numeric', minute: 'numeric', second: 'numeric' }
  ).format(new Date(2018, 0, 1, 21, 37, 14))
);
```

which gives me this output locally

```
9:37:14 PM
21:37:14
```
and this one on Travis:

```
9:37:14 PM
9:37:14 PM
```

now at least I know it's not my fault directly... I'm on it!

**Comment by forrestbice** [comment]
@wojtekmaj nice detective work! Sounds like things are coming along nicely and this is getting pretty close to merging 😄  🎉

**Comment by wojtekmaj** [comment]
Yep! During manual testing it became apparent we need much more unit tests than I initially thought, so I'll write them soon. I'm also waiting for Travis support to reply.

**Comment by forrestbice** [comment]
@wojtekmaj great, looking forward to the next update!

**Pull request merged**
