### PR TITLE
Parse out . from values that come in before attempting to process

### PR DESCRIPTION
**Pull request by emilyuhde**
Since this is my first PR to the repo, I have a couple questions.

1. When I try running the sample page, it doesn't seem to bring in these updates, so I can't veryify this will work. Is there something special I need to do to have changes to the src code reflected on the sample page? (I will need to fix the issue breaking the build once I figure out how to properly test the change.)

2. I wasn't sure what type of unit tests I should add for this issue as I can only repro it when I manually enter a non-into number into one of the TimePicker inputs. It won't work if I jsut set the initial value to something with a . in it. It seems like it's something that needs to be tested with regression or integration testing that does UI validation, not unit tests.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hi! Good questions.

`/sample` and `/test` folders are a separate repos. By default, they install the package from NPM. This allows me to autodeploy these pages when I need it :)

Should you wish to use local react-time-picker:
* Ensure you installed react-time-picker package
* Run `yarn link`
* Go to `/sample` or `/test`
* Run `yarn link react-time-picker`

This will cause sample/test pages to use your WIP code instead of published stable one.

**Comment by wojtekmaj** [comment]
I wonder what are you trying to fix here?

I'm worried that some browsers may actually send value like "4.0" which is changed to "40" by this change.

**Comment by emilyuhde** [comment]
Thanks for the information about how to run this!

If you have suggestions for a better fix, I'm happy to hear them! My thought was that this fix could just parse out and ignore when users type in . as part of the number (the UI should reflect this too, there shoud be no more . after we parse it out, so I will need to move where in the code this happens). It seemed to me like this behavior would be good since it would mimic Chrome which won't let you type letter characters into the inputs at all. I don't know if we would want to change the behavior to something like if you type in 5.5 minutes, it would convert it to 5 minutes and add 30 seconds into the seconds input, if it is present. That seemed like undesirable behvaior, changing the values in the other inputs, since anything less than a whole number is not valid for clock times.

**Comment by emilyuhde** [comment]
@wojtekmaj Another possibility would be to use catch exceptions from the TimePicker in the component files that are using it. That's what I ended up doing to stop the crashes in my project.


```

/**
     * Catch any errors thrown by the underlying TimePicker component.
     *
     * @param {Error} error  The error itself
     * @param {object} info  Componet stack info
     */
    componentDidCatch(error, info) {
        console.error(`Caught error: ${info.componentStack}`);
    }
```

    /**
     * Get new state after an exception
     */
    static getDerivedStateFromError() {
        // We don't need to change anything about the state, but we need to return
        // *something* for this to work
        return { };
    }

**Comment by wojtekmaj** [comment]
@emilyuhde 

Regarding bonduaries: I don't think we can allow for any crashes to happen. I'd rather have them fixed, and leave error boundaries to the developers, they might not want to put them in place for various reasons (like automated tests looking for crashed, empty page).

Regarding the picker itself: I fixed this issue by parsing integers - `parseInt(1.0)` returns `1` so that's exactly what we would like to see. Your fix changes `1.0` to `10` which I don't think is expected. I'll close this PR as our fixes are overlapping. Hope you don't mind!

Thank you for pointing that out, though! Fix for the issue you've found was also applied to React-Date-Picker, React-DateRange-Picker, React-TimeRange-Picker, and a few other libraries :D

**Comment by emilyuhde** [comment]
Sounds good, glad it's getting fixed! Are you planning a patch release soon? @wojtekmaj

**Comment by wojtekmaj** [comment]
3 AM at my place so probably a bad time to release something to at least 640 known users :D Definitely not today, will try to do this over the weekend.

**Comment by emilyuhde** [comment]
I didn't mean today when I said "soon" haha!

**Pull request closed without merging**
