### PR TITLE
Fix  - Focus jumps from hours field to seconds field, missing the minutes field.

### PR DESCRIPTION
**Pull request by IndraManickam**
https://github.com/wojtekmaj/react-time-picker/issues/282

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Doesn't look like the way to go, why would we wait before focusing the next input? This will actually break date input if you're typing too fast.

**Comment by IndraManickam** [comment]
@wojtekmaj the wait is actually introduced only to fix the date input if the user is typing in too fast.
If there are two key up happening rapidly from one field, it should stay that way. From the user's perspective, he is typing in the value on the hour field. but since we have the move focus function in-between, as per the browser the focus moves to the minute field, and the second key up results as the event target minute field.  I have described the issue on https://github.com/wojtekmaj/react-time-picker/issues/282.

1. Set the minute value as 53.
2. Rapidly type '12' on the hour field.
3. The focus will move to the seconds' field.
4. If the user type '12' slowly the focus moves to the minute field.
5. Setting the delay for the focus will still keep the focus in the minute field only.

**Comment by IndraManickam** [comment]
@wojtekmaj Please let me know if you need more information.

**Comment by wojtekmaj** [comment]
The correct way to fix this, it seems, is to prevent onKeyUp event from happening if two key presses overlap each other. setTimeout is not the way to do this, but thanks for the insight!

**Pull request closed without merging**
